on:
    workflow_dispatch:
# Removed invalid line
jobs:
  agent-install:
    runs-on: self-hosted
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20.0
  build-check:
    name: Build with CHECK_LINKS and CHECK_FLAGS
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Build with the latest action rev
      uses: jbilinski/mugtrap@main
      env:
        BUILD_ONLY: true
        BUILD_DIR: public
        CHECK_LINKS: true
        CHECK_FLAGS: --draft